<?xml version="1.0"?>
<robot name="lunar_rover" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ==================== PROPERTIES ==================== -->
  <xacro:property name="chassis_length" value="0.6"/>
  <xacro:property name="chassis_width" value="0.4"/>
  <xacro:property name="chassis_height" value="0.2"/>
  <xacro:property name="chassis_mass" value="10.0"/>
  
  <xacro:property name="wheel_radius" value="0.15"/>
  <xacro:property name="wheel_width" value="0.1"/>
  <xacro:property name="wheel_mass" value="1.0"/>
  <xacro:property name="wheel_separation" value="0.5"/>
  <xacro:property name="wheelbase" value="0.4"/> <!-- Distance between front and rear axles -->
  
  <!-- ==================== MATERIALS ==================== -->
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  
  <material name="black">
    <color rgba="0.1 0.1 0.1 1"/>
  </material>
  
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1"/>
  </material>

  <!-- ==================== BASE FOOTPRINT ==================== -->
  <link name="base_footprint"/>

  <!-- ==================== BASE LINK (Chassis) ==================== -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 -0.1" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <inertia 
        ixx="${(chassis_mass/12) * (chassis_width*chassis_width + chassis_height*chassis_height)}" 
        ixy="0" 
        ixz="0"
        iyy="${(chassis_mass/12) * (chassis_length*chassis_length + chassis_height*chassis_height)}" 
        iyz="0"
        izz="${(chassis_mass/12) * (chassis_length*chassis_length + chassis_width*chassis_width)}"/>
    </inertial>
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- ==================== WHEEL MACRO ==================== -->
  <xacro:macro name="wheel" params="prefix x y">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="1.5707963 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="1.5707963 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 0" rpy="1.5707963 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia 
          ixx="${(wheel_mass/12) * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
          ixy="0" 
          ixz="0"
          iyy="${(wheel_mass/12) * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
          iyz="0"
          izz="${(wheel_mass/2) * wheel_radius*wheel_radius}"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${x} ${y} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <gazebo reference="${prefix}_wheel">
      <material>Gazebo/Black</material>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>500000.0</kp>
      <kd>10.0</kd>
      <minDepth>0.001</minDepth>
    </gazebo>
  </xacro:macro>

  <!-- ==================== ADD 4 WHEELS ==================== -->
  <!-- Front Left -->
  <xacro:wheel prefix="front_left" x="${wheelbase/2}" y="${wheel_separation/2}"/>
  <!-- Front Right -->
  <xacro:wheel prefix="front_right" x="${wheelbase/2}" y="${-wheel_separation/2}"/>
  <!-- Rear Left -->
  <xacro:wheel prefix="rear_left" x="${-wheelbase/2}" y="${wheel_separation/2}"/>
  <!-- Rear Right -->
  <xacro:wheel prefix="rear_right" x="${-wheelbase/2}" y="${-wheel_separation/2}"/>

  <!-- ==================== DEPTH CAMERA ==================== -->
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="blue"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
    
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${chassis_length/2} 0 ${chassis_height/2 + 0.1}" rpy="0 0.349 0"/>
  </joint>

  <!-- ==================== IMU ==================== -->
  <link name="imu_link">
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- ==================== GAZEBO PLUGINS ==================== -->
  
  <!-- 1. SKID STEER DRIVE (ROS 2) -->
  <!-- Using diff_drive plugin on 4 wheels behaves like skid steer if we map pairs -->
  <!-- Note: Gazebo's "skid_steer_drive" is often buggy in ROS 2. 
       A common workaround is to use diff_drive with 2 virtual wheels or map all 4. 
       Ideally, we use the `libgazebo_ros_diff_drive.so` and specify num_wheel_pairs if supported, 
       or just link front/rear wheels. 
       SIMPLER: We will use the proper skid steer plugin if available, or just map 'front' wheels for control and let rear follow (if no physics constraint) or map all.
       
       Let's use the explicit skid steer plugin for reliability on 4 wheels.
  -->
  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/</namespace>
        <remapping>cmd_vel:=/cmd_vel</remapping>
        <remapping>odom:=odom</remapping>
      </ros>
      <update_rate>50.0</update_rate>
      
      <!-- Number of wheel pairs -->
      <num_wheel_pairs>2</num_wheel_pairs>
      
      <!-- Front pair -->
      <left_joint>front_left_wheel_joint</left_joint>
      <right_joint>front_right_wheel_joint</right_joint>
      
      <!-- Rear pair -->
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>rear_right_wheel_joint</right_joint>
      
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>
      
      <max_wheel_torque>200</max_wheel_torque>
      <max_wheel_acceleration>2.0</max_wheel_acceleration>
      
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>

    </plugin>
  </gazebo>

  <!-- 2. DEPTH CAMERA (ROS 2) -->
  <gazebo reference="camera_link">
    <sensor type="depth" name="depth_camera">
      <always_on>true</always_on>
      <update_rate>10.0</update_rate>
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.5</near>
          <far>50.0</far>
        </clip>
      </camera>
      
      <plugin name="depth_camera_controller" filename="libgazebo_ros_camera.so">
        <ros>
          <namespace>/camera</namespace>
          <remapping>depth_camera/image_raw:=depth/image_raw</remapping>
          <remapping>depth_camera/camera_info:=depth/camera_info</remapping>
          <remapping>depth_camera/points:=depth/points</remapping>
        </ros>
        
        <camera_name>depth_camera</camera_name>
        <frame_name>camera_link</frame_name>
        <hack_baseline>0.07</hack_baseline>
        <min_depth>0.5</min_depth>
        <max_depth>50.0</max_depth>
      </plugin>
    </sensor>
  </gazebo>

  <!-- 3. IMU (ROS 2) -->
  <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100.0</update_rate>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <ros>
          <namespace>/</namespace>
          <remapping>~/out:=imu</remapping>
        </ros>
        <initial_orientation_as_reference>false</initial_orientation_as_reference>
      </plugin>
    </sensor>
  </gazebo>

  <!-- ==================== GAZEBO MATERIALS ==================== -->
  <gazebo reference="base_link">
    <material>Gazebo/White</material>
  </gazebo>


  <!-- 4. P3D (Ground Truth) -->
  <gazebo>
    <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
      <ros>
        <remapping>odom:=/ground_truth</remapping>
      </ros>
      <body_name>base_footprint</body_name>
      <update_rate>50.0</update_rate>
      <xyz_offset>0 0 0</xyz_offset>
      <rpy_offset>0 0 0</rpy_offset>
      <gaussian_noise>0.0</gaussian_noise>
    </plugin>
  </gazebo>

</robot>

